language: ruby
bundler_args: --without development
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
#notifications:
  #recipients:
    #- ferdev@vizzuality.com
branches:
  only:
    - master
