host: 'https://gfw-test.cartodb.com'
oauth_key: 'Myhiv4bMCBRMhdDt1AjRUsfvbzHuNixVEmLZSEJ4'
oauth_secret: 'aIop36RxDohptnDiGJbhjANJEjwBRmdyYIEM00Da'
username: 'gfw-test'
password: 'gfw-test'
host: https://wri-01.cartodb.com
api_key: 0e5365cb1a299778e9df9c7bf6db489af8aa08e1
